const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, LevelFormat } = require("docx");

const paragraphs = [
  new Paragraph({ text: "Sapphire Pipeline Workflow", style: "Heading1" }),
  new Paragraph({ text: `Prompt: "Where is Quiver data insufficient to support this hypothesis?"`, style: "Heading2" }),
  new Paragraph({ text: "This document defines the complete Sapphire pipeline — the sequential stages, tools called, external datasets used, inputs, outputs, and decision logic — required to deliver a valid, actionable answer to this prompt." }),
  new Paragraph({ text: "Pipeline Overview", style: "Heading2" }),
  new Paragraph({ text: "The Sapphire Pipeline for data sufficiency assessment systematically evaluates the robustness of internal Quiver datasets relative to scientific and regulatory hypotheses central to drug development decisions. This pipeline identifies gaps in data volume, granularity, duration, population coverage, and quality that could undermine PoS estimates or clinical trial outcomes, and recommends targeted data collection or external validation studies." }),
  new Paragraph({ text: "The assessment integrates statistical power analysis, regulatory precedent evaluation, and external benchmark comparisons to quantify the impact of data insufficiency on decision confidence. Results guide prioritization of data generation investments, external partnership needs, and risk mitigation strategies for programs where Quiver data is inadequate to support the underlying scientific hypothesis." }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 1: Hypothesis Definition & Data Requirements Specification", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Articulate the specific scientific or clinical hypothesis driving program decisions, define the data requirements (sample size, granularity, duration) needed to validate it, and identify the relevant Quiver datasets.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Scientific hypothesis statement and mechanism of action assumptions underlying the program", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Regulatory expectations and precedent guidance for clinical trial design and endpoints", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Target population definition and patient stratification criteria", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Historical trial data from comparable programs and indications", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Current inventory of internal Quiver datasets relevant to the hypothesis", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Sapphire Hypothesis Validation Framework: ", bold: true }), new TextRun("Structured methodology for translating scientific hypotheses into testable data requirements")] }),
  new Paragraph({ children: [new TextRun({ text: "FDA Guidance Documents: ", bold: true }), new TextRun("Indication-specific trial design, endpoint selection, and data collection requirements")] }),
  new Paragraph({ children: [new TextRun({ text: "Clinical Trial Design Standards: ", bold: true }), new TextRun("ICH, EMA, and regulatory expectations for data quality and completeness")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Data Inventory System: ", bold: true }), new TextRun("Comprehensive catalog of all internal datasets with sample size, duration, and population coverage")] }),
  new Paragraph({ children: [new TextRun({ text: "Historical Trial Analytics: ", bold: true }), new TextRun("Comparable program outcomes and effect size benchmarks")] }),
  new Paragraph({ children: [new TextRun({ text: "Meta-Analysis & Systematic Review Databases: ", bold: true }), new TextRun("Published evidence on effect sizes and variability in comparable patient populations")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What is the precise hypothesis we are testing with this program?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What data characteristics (N, duration, population) are needed to test it with adequate power?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the expected effect size based on literature and historical data?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What regulatory data expectations exist for this indication and development stage?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What Quiver datasets are relevant to this hypothesis and what are their characteristics?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Clearly articulated hypothesis statement with mechanistic rationale and expected clinical benefit", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Data requirements specification: required sample size, follow-up duration, and population characteristics", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Regulatory expectations summary from FDA and international guidance documents", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Literature-based effect size and variance estimates with confidence intervals", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Inventory of relevant Quiver datasets with current sample sizes and population coverage", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Preliminary gap analysis mapping Quiver data availability against requirements", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Hypothesis specification document with data requirements matrix and preliminary gap summary.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 2: Quiver Data Completeness & Quality Assessment", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Conduct comprehensive audit of Quiver datasets to assess completeness (missing data %), quality (accuracy, consistency), and suitability for hypothesis testing.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Raw Quiver datasets from relevant therapeutic programs and indications", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Data dictionary definitions and variable specifications", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Study protocols and case report form (CRF) specifications", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Data validation and quality control procedures documented in project reports", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Patient inclusion/exclusion criteria and population stratification logic", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Data Quality Assessment Toolkit: ", bold: true }), new TextRun("Completeness, consistency, and accuracy metrics for Quiver datasets")] }),
  new Paragraph({ children: [new TextRun({ text: "Missing Data Analysis Framework: ", bold: true }), new TextRun("Characterization of missing data patterns and imputation feasibility assessment")] }),
  new Paragraph({ children: [new TextRun({ text: "Statistical Validation Engine: ", bold: true }), new TextRun("Outlier detection, distributional analysis, and anomaly flagging")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Data Warehouse: ", bold: true }), new TextRun("Centralized repository with query capabilities and data lineage tracking")] }),
  new Paragraph({ children: [new TextRun({ text: "Laboratory & Assay QC Database: ", bold: true }), new TextRun("Analytical validation results and assay performance metrics")] }),
  new Paragraph({ children: [new TextRun({ text: "Electronic Health Record (EHR) Integrity Tools: ", bold: true }), new TextRun("Validation of clinical assessment timing, clinical investigator consistency, and source data verification")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What percentage of data points are missing across key variables in each dataset?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Are there systematic patterns to the missing data (e.g., dropout, poor sites)?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What data quality issues or anomalies were identified during trial conduct or data review?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the source data verification rate and were corrections made post-database lock?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How consistent are assessments across study sites and clinical assessors?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Data completeness report by dataset and by variable with missing data percentages and patterns", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Data quality assessment: outliers, consistency checks, and anomaly flagging results", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Source data verification status and documentation of corrections made", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Laboratory and assay analytical validation results with performance metrics", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Inter-rater reliability and site-to-site consistency analysis for clinical assessments", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quality scoring of each Quiver dataset (e.g., high/medium/low confidence rating)", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Data quality audit report with completeness matrices, consistency analysis, and quality scorecards.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 3: Statistical Power Analysis & Sample Size Assessment", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Conduct quantitative assessment of whether Quiver data sample sizes are sufficient to detect the hypothesized effect size with adequate statistical power.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Data requirements specification from Stage 1", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quiver dataset sample sizes and population characteristics from Stage 2", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Effect size estimates from literature and historical data", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Variance estimates and data variability (within-subject, between-subject, site-to-site)", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Dropout rates and missing data patterns observed in Quiver data", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Sapphire Power Analysis Engine: ", bold: true }), new TextRun("Bayesian and frequentist power calculations with various study designs and effect sizes")] }),
  new Paragraph({ children: [new TextRun({ text: "Statistical Simulation Tools (R, Python): ", bold: true }), new TextRun("Monte Carlo simulations of trial outcomes under observed data variability")] }),
  new Paragraph({ children: [new TextRun({ text: "Effect Size Meta-Analyses: ", bold: true }), new TextRun("Systematic reviews and meta-analyses for comparable populations and endpoints")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Historical PoS Database: ", bold: true }), new TextRun("De-identified trial outcomes and effect size distributions by program phase and indication")] }),
  new Paragraph({ children: [new TextRun({ text: "Variance Component Analysis: ", bold: true }), new TextRun("Decomposition of variance sources (sites, assessors, measurement error) in Quiver data")] }),
  new Paragraph({ children: [new TextRun({ text: "Adaptive Design Operating Characteristics: ", bold: true }), new TextRun("Power analysis for trials with interim analyses and sample size re-estimation rules")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What is the statistical power of current Quiver data to detect the hypothesized effect size?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How many additional subjects would be needed to achieve 90% power?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How sensitive is our conclusion to changes in assumed effect size or variance?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Can we adequately power subgroup analyses for patient stratification?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Would an adaptive design with interim analyses improve power given current data variability?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Power analysis report with sample size requirements for different effect sizes and power levels", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Sensitivity analysis: power curves across ranges of effect size and variance assumptions", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Subgroup analysis power assessment for key patient stratification variables", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Recommendations for study design optimization (e.g., outcome enrichment, adaptive design)", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Monte Carlo simulation results showing success probability under observed data characteristics", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Gap quantification: current sample size vs. powered sample size for each major analysis", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Statistical power analysis report with power curves, sample size tables, and sensitivity analyses.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 4: Population Coverage & Generalizability Assessment", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Evaluate whether Quiver data populations are representative of intended patient populations, and quantify generalizability limitations and external validity concerns.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Quiver study inclusion/exclusion criteria and enrolled population demographics", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Target commercial population definition for intended indication and patient segment", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "National/international epidemiologic data on disease prevalence and population characteristics", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Published patient registries and real-world data from comparable indications", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Genetic, demographic, and clinical stratification variables relevant to treatment response", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Generalizability Assessment Framework: ", bold: true }), new TextRun("Structured methodology comparing trial populations to target populations")] }),
  new Paragraph({ children: [new TextRun({ text: "Population Demographics Databases: ", bold: true }), new TextRun("Census data, epidemiologic registries, and real-world patient characteristics")] }),
  new Paragraph({ children: [new TextRun({ text: "Disease Registries (NORD, Orphanet, NIH): ", bold: true }), new TextRun("Patient population characteristics and natural history data for specific indications")] }),
  new Paragraph({ children: [new TextRun({ text: "Real-World Evidence Platforms: ", bold: true }), new TextRun("Electronic health records and claims databases capturing diverse patient populations")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Patient Database: ", bold: true }), new TextRun("De-identified demographic, genetic, and clinical data across all programs")] }),
  new Paragraph({ children: [new TextRun({ text: "Subgroup Analysis & Interaction Testing: ", bold: true }), new TextRun("Statistical tests for treatment effect heterogeneity across demographic and clinical subgroups")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "How representative are Quiver study populations compared to the broader disease population?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What are the key demographic and clinical differences between study and target populations?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Are there subgroups in Quiver data showing substantially different treatment effects?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How would results differ if we included more severe or more comorbid patients?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Do we have adequate representation of diverse populations (age, gender, race/ethnicity)?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Population characteristics comparison: Quiver studies vs. target populations and epidemiologic data", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Generalizability assessment scoring: identified limitations and potential external validity threats", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Subgroup analysis: treatment effect estimates across demographic and clinical subgroups", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Diversity assessment: representation of age, gender, race/ethnicity, and comorbidity profiles", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Real-world effectiveness potential: predicted outcomes in broader populations based on subgroup data", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Recommendations for additional studies or real-world data collection to validate findings", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Population coverage report with demographic comparison tables, subgroup effect estimates, and generalizability conclusions.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 5: Temporal Coverage & Natural History Validation", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Assess whether Quiver data follow-up duration is adequate to capture the full disease trajectory and long-term treatment effects relevant to the hypothesis.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Quiver study designs and follow-up durations across programs", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Natural history studies and placebo progression data for the indication", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected treatment effect timeline (onset, durability, plateau vs. decline)", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Long-term safety monitoring data and delayed adverse event patterns", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Disease relapse rates and disease modification endpoints from literature", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Natural History Database: ", bold: true }), new TextRun("Longitudinal data on disease progression without intervention")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Follow-up Extension Studies: ", bold: true }), new TextRun("Long-term outcome and durability data from open-label continuation studies")] }),
  new Paragraph({ children: [new TextRun({ text: "Real-World Claims & EHR Data: ", bold: true }), new TextRun("Longer follow-up periods and real-world treatment durability patterns")] }),
  new Paragraph({ children: [new TextRun({ text: "Safety Surveillance System: ", bold: true }), new TextRun("Adverse event patterns over extended follow-up and post-marketing experience")] }),
  new Paragraph({ children: [new TextRun({ text: "Disease Progression Models: ", bold: true }), new TextRun("Predictive models of untreated disease trajectory and cumulative morbidity risk")] }),
  new Paragraph({ children: [new TextRun({ text: "Endpoint Maturation Analysis: ", bold: true }), new TextRun("Statistical assessment of whether follow-up duration is sufficient to assess primary endpoints")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "Is the follow-up duration in Quiver data sufficient to assess the primary hypothesis?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the natural history timeline for this disease and how does our follow-up compare?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Do we have adequate long-term safety data (e.g., 1-2 years) relative to regulatory expectations?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could delayed or waning treatment effects alter conclusions if extended follow-up were available?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the maturity of our primary endpoint and how likely is it to change with longer follow-up?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Temporal coverage assessment: Quiver follow-up duration vs. disease natural history timeline", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Natural history validation: comparison of placebo/control progression to literature baselines", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Long-term safety profile characterization with adverse event frequency and timing", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Primary endpoint maturity assessment and probability of endpoint change with extended follow-up", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Treatment durability and relapse/recurrence patterns in available long-term data", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Recommendations for follow-up duration extensions or post-marketing studies", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Temporal coverage report with natural history timelines, safety tables, and endpoint maturity assessments.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 6: Data Gap Remediation & Recommendations", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Synthesize all insufficiency findings into prioritized recommendations for targeted data generation, external partnerships, or re-analysis strategies to strengthen hypothesis validation.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Comprehensive findings from Stages 1-5: completeness, quality, power, generalizability, and temporal gaps", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "PoS impact modeling: how each data gap affects probability of regulatory approval or trial success", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Available budgets and timelines for data generation or external studies", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Regulatory expectations and precedent guidance for data sufficiency in this indication", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Strategic priorities: which gaps are critical vs. nice-to-have from a development perspective", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Gap Remediation Framework: ", bold: true }), new TextRun("Prioritization methodology for addressing data insufficiencies")] }),
  new Paragraph({ children: [new TextRun({ text: "Clinical Study Design Tools: ", bold: true }), new TextRun("Design specifications for supplementary studies to fill identified gaps")] }),
  new Paragraph({ children: [new TextRun({ text: "Real-World Data Partnerships: ", bold: true }), new TextRun("Opportunities for external data partnerships and RWE study designs")] }),
  new Paragraph({ children: [new TextRun({ text: "Budget Impact & Resource Modeling: ", bold: true }), new TextRun("Cost estimates and feasibility assessment for recommended studies")] }),
  new Paragraph({ children: [new TextRun({ text: "Re-Analysis Methodologies: ", bold: true }), new TextRun("Statistical approaches (e.g., Bayesian borrowing, meta-analysis) to maximize information from existing data")] }),
  new Paragraph({ children: [new TextRun({ text: "Regulatory Success Prediction Models: ", bold: true }), new TextRun("Bayesian forecast of approval probability with and without remediation strategies")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What are the most critical data gaps that must be addressed to support program advancement?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could we address gaps through re-analysis, external data partnerships, or supplementary studies?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the impact of each data gap on program PoS and regulatory approval probability?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the cost and timeline for recommended remediation studies?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How would addressing these gaps increase program success probability and valuation?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Comprehensive data insufficiency report with prioritized gaps ranked by criticality and impact", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Gap remediation roadmap with specific studies, external partnerships, and re-analysis approaches", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "PoS impact modeling: forecasted approval probability with and without remediation strategies", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Budget and timeline estimates for recommended remediation activities", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Regulatory strategy: how remediation aligns with FDA expectations and approval pathway", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Go/no-go recommendations: program advancement criteria based on feasible gap remediation", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Data insufficiency findings report with gap prioritization matrices, remediation roadmap, and PoS impact projections.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Summary", style: "Heading2" }),
  new Paragraph({ text: "Sapphire Hypothesis Validation Framework: Structured methodology for translating scientific hypotheses into testable data requirements and study designs", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "FDA Guidance Documents: Therapeutic area-specific trial design, endpoint selection, and data collection expectations", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Clinical Trial Design Standards: ICH guidelines, regulatory expectations, and international data quality standards", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quiver Data Inventory System: Comprehensive catalog of internal datasets with characterization of sample sizes, populations, duration, and data quality metrics", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Historical Trial Analytics: De-identified Quiver program outcomes, effect sizes, and variance estimates by program phase and indication", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Meta-Analysis & Systematic Review Databases: Published literature on effect sizes, variance, and outcomes in comparable patient populations and conditions", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Data Quality Assessment Toolkit: Metrics for completeness, consistency, accuracy, and anomaly detection across datasets", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Missing Data Analysis Framework: Characterization of missing data patterns and assessment of imputation feasibility", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Statistical Validation Engine: Outlier detection, distributional analysis, and statistical quality control procedures", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quiver Data Warehouse: Centralized repository of internal datasets with query capabilities and data lineage tracking", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Laboratory & Assay QC Database: Analytical validation results, assay performance metrics, and precision/accuracy reports", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Electronic Health Record (EHR) Integrity Tools: Validation of clinical assessment timing, assessor consistency, and source data verification rates", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Sapphire Power Analysis Engine: Bayesian and frequentist power calculations with design flexibility and assumption sensitivity analysis", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Statistical Simulation Tools: Monte Carlo simulations for trial operating characteristics under observed data variability and design parameters", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Effect Size Meta-Analyses: Systematic reviews quantifying effect sizes and variance distributions in comparable populations and therapeutic areas", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quiver Historical PoS Database: De-identified trial outcomes and probability of success distributions by program phase, indication, and drug class", numbering: { reference: "bullets", level: 0 } }),
];

const doc = new Document({
  numbering: { config: [{ reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "\u2022", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }, { level: 1, format: LevelFormat.BULLET, text: "\u2022", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1440, hanging: 360 } } } }] }] },
  styles: { default: { document: { run: { font: "Arial", size: 24 } } }, paragraphStyles: [{ id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial" }, paragraph: { spacing: { before: 240, after: 240 } } }, { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 28, bold: true, font: "Arial" }, paragraph: { spacing: { before: 200, after: 200 } } }] },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } }, children: paragraphs }]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync("/sessions/youthful-vigilant-planck/mnt/Desktop/Sapphire Prompt Work_Feb 2026/Sapphire Pipelines/Pipeline_155.docx", buffer);
  console.log("Pipeline_155.docx created with " + paragraphs.length + " paragraphs");
});
