const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, LevelFormat } = require("docx");

const paragraphs = [
  new Paragraph({ text: "Sapphire Pipeline Workflow", style: "Heading1" }),
  new Paragraph({ text: `Prompt: "Simulate outcome if top 2 programs fail — what is backup plan?"`, style: "Heading2" }),
  new Paragraph({ text: "This document defines the complete Sapphire pipeline — the sequential stages, tools called, external datasets used, inputs, outputs, and decision logic — required to deliver a valid, actionable answer to this prompt." }),
  new Paragraph({ text: "Pipeline Overview", style: "Heading2" }),
  new Paragraph({ text: "The Sapphire Pipeline for catastrophic failure scenario analysis simulates the business impact of simultaneous failure of the company's two highest-value programs and systematically evaluates contingency strategies to preserve financial viability and strategic positioning. This pipeline models loss of revenue projections, pipeline disruption, competitive implications, and stakeholder confidence, then identifies bridge programs, licensing opportunities, and organizational pivots that would position the company for recovery." }),
  new Paragraph({ text: "The analysis integrates financial forecasting, competitive landscape modeling, partnership opportunities, and acceleration pathways for remaining programs to develop actionable backup plans. Each contingency strategy is evaluated against feasibility, capital requirements, time-to-revenue milestones, and probability of success to ensure that leadership has realistic options should catastrophic failure occur." }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 1: Top 2 Programs Identification & Failure Impact Modeling", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Identify the company's two highest-value programs by NPV and market impact, model the financial and strategic consequences of their simultaneous failure, and quantify the magnitude of the crisis.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Current portfolio programs with program-level revenue and PoS projections", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Clinical trial timelines and upcoming Phase 2b/3 decision milestones for all programs", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Peak sales projections and market size estimates for each indication", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Historical failure rates and failure drivers by program phase and indication", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Current debt obligations, capital expenditure commitments, and runway estimates", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Sapphire NPV Calculator: ", bold: true }), new TextRun("Risk-adjusted NPV computation integrating probability, discount rates, and commercial parameters")] }),
  new Paragraph({ children: [new TextRun({ text: "Financial Modeling System: ", bold: true }), new TextRun("Multi-scenario cash flow analysis and balance sheet impact projection")] }),
  new Paragraph({ children: [new TextRun({ text: "Cortellis Market Intelligence: ", bold: true }), new TextRun("Peak sales estimates, market growth rates, and competitive pricing intelligence")] }),
  new Paragraph({ children: [new TextRun({ text: "Historical Trial Outcomes Database: ", bold: true }), new TextRun("Phase-specific and indication-specific failure rate benchmarks")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Financial Planning Tools: ", bold: true }), new TextRun("Cash flow stress-testing and runway calculations under various scenarios")] }),
  new Paragraph({ children: [new TextRun({ text: "Industry Valuation Models: ", bold: true }), new TextRun("Biotech company valuation multiples and equity impact estimation")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What are the two programs with highest NPV and regulatory milestone certainty?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What would be the cumulative revenue loss if both programs fail?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How long would the company's cash runway be post-failure without intervention?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the probability of simultaneous failure given current trial enrollment and assumptions?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How would stock price and equity funding access be impacted by dual failure?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Top 2 programs ranking with NPV, revenue impact, and timeline to commercial value", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Integrated failure impact model showing cash position trajectory post-failure", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Financial metrics: months to cash depletion, required cost reductions, and capital needs", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Equity valuation impact analysis and comparison to industry failure precedents", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Pipeline risk concentration metrics and program independence analysis", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Critical assumptions underlying risk analysis with sensitivity ranges", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Crisis impact summary with financial waterfall charts, runway projection graphs, and risk concentration matrices.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 2: Bridge Program Acceleration & Out-Licensing Opportunities", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Identify programs in Stage 2-3 that could be accelerated to generate near-term revenue, and evaluate out-licensing or partnership opportunities that could monetize remaining pipeline assets.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Complete portfolio inventory with program stage, modality, and development timeline", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Preclinical and early clinical data packages and regulatory readiness status", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Competitive programs in advanced stages and market opportunity assessments", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Out-licensing benchmarks and partnership valuations from recent deals", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Emerging biology and adjacent indication opportunities for program repurposing", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Sapphire Program Acceleration Engine: ", bold: true }), new TextRun("Timeline optimization accounting for resource availability, regulatory pathway, and probability constraints")] }),
  new Paragraph({ children: [new TextRun({ text: "BioPharma Intelligence Platform: ", bold: true }), new TextRun("Strategic partnerships, licensing deals, and M&A precedent valuation data")] }),
  new Paragraph({ children: [new TextRun({ text: "Drug Hunter & Excelra: ", bold: true }), new TextRun("Deal benchmarking and licensing valuation metrics by therapeutic area")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Partner Network Database: ", bold: true }), new TextRun("Identified pharma and biotech partners with interest in adjacent indications and programs")] }),
  new Paragraph({ children: [new TextRun({ text: "Regulatory Fast-Track Eligibility Assessment: ", bold: true }), new TextRun("Breakthrough, orphan drug, and accelerated approval pathway qualification for bridge programs")] }),
  new Paragraph({ children: [new TextRun({ text: "Indication Mapping Tools: ", bold: true }), new TextRun("Off-label and adjacent indication opportunities for existing program assets")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "Which Stage 2/3 programs could reach Phase 3 readiness within 18 months with acceleration?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the revenue timeline and probability-adjusted value of each bridge program?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Which programs are attractive out-licensing candidates and to whom (identify pharma partners)?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could we generate $50M+ in near-term partnerships or licensing deals?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Are there adjacent indications or patient populations where programs could be rapidly repositioned?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Prioritized bridge program list with acceleration timeline, probability-adjusted revenue, and capital requirements", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Program-by-program acceleration roadmaps with key milestones and go/no-go decision gates", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Out-licensing opportunity matrix with identified partners and estimated valuation ranges", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Partnership deal structure recommendations and negotiation priorities", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Indication repurposing opportunities with clinical pathway feasibility assessments", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Projected cumulative near-term revenue from bridge programs and licensing deals", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Strategic partnership roadmap with program timelines, partner lists, and valuation summaries.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 3: In-Licensing & Acquisition Strategies", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Identify clinical-stage assets that could be rapidly in-licensed or acquired to replace lost revenue from top 2 program failures, prioritizing programs with expedited regulatory pathways and near-term approval potential.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Marketplace inventory of partnered programs seeking new homes or seeking co-promotion", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Available capital for in-licensing fees and milestone payments", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Preferred therapeutic areas, modalities, and stage of development", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Biotech company and university licensing catalogs with available programs", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Competitive program landscape and market pricing expectations", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "BioPharma Licensing Intelligence Platform: ", bold: true }), new TextRun("In-licensing opportunities, deal terms, and up-front fee benchmarking")] }),
  new Paragraph({ children: [new TextRun({ text: "BioMedReports & Evaluate Pharma: ", bold: true }), new TextRun("Available programs, deal structures, and licensing precedent valuations")] }),
  new Paragraph({ children: [new TextRun({ text: "ClinicalTrials.gov Search: ", bold: true }), new TextRun("Identify late-stage programs and partnered assets seeking new licensees")] }),
  new Paragraph({ children: [new TextRun({ text: "University Technology Transfer Offices: ", bold: true }), new TextRun("Academic programs available for licensing in target therapeutic areas")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver M&A Database: ", bold: true }), new TextRun("Identified acquisition targets with synergistic programs and valuations")] }),
  new Paragraph({ children: [new TextRun({ text: "Strategic Fit Analysis Tools: ", bold: true }), new TextRun("Portfolio complementarity assessment and organizational integration feasibility")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What clinical-stage programs are currently available for in-licensing in our therapeutic focus areas?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Which programs have the highest probability of approval within 2-3 years?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the estimated upfront cost for in-licensing deals that could address the revenue gap?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Are there smaller biotech companies that could be acquired for their pipeline assets?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What integration costs and timelines would be required for successful asset acquisition?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "In-licensing opportunity pipeline with stage, indication, modality, and valuation estimates", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Strategic fit assessment for each acquisition target with synergy analysis", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Prioritized in-licensing recommendations based on risk-adjusted NPV and timeline", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Financial modeling: estimated upfront fees, milestone payments, and royalties by opportunity", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "M&A feasibility assessment: integration costs, regulatory requirements, and organizational fit", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Deal structure recommendations and negotiation strategy for priority opportunities", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("In-licensing market analysis with opportunity pipeline ranking, financial modeling summaries, and deal structure recommendations.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 4: Cost Structure Optimization & Runway Extension", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Identify cost reduction opportunities and operational efficiencies that would extend cash runway, reduce capital requirements, and preserve equity.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Current organizational headcount, salary structure, and department budgets", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Current contract manufacturing and supply chain costs by program and by function", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Geographic footprint and real estate commitments with lease terms", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Technology and infrastructure spending with prioritization scoring", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Outsourcing benchmarks and alternative service provider cost models", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Biotech Cost Benchmarking Database: ", bold: true }), new TextRun("FTE, salary, and overhead costs by function and by company stage")] }),
  new Paragraph({ children: [new TextRun({ text: "Contract Manufacturing Analysis: ", bold: true }), new TextRun("COGS reduction opportunities and alternative manufacturing partners")] }),
  new Paragraph({ children: [new TextRun({ text: "CRO & Consulting Cost Models: ", bold: true }), new TextRun("Outsourcing vs. insourcing analysis and service provider pricing")] }),
  new Paragraph({ children: [new TextRun({ text: "Real Estate Market Intelligence: ", bold: true }), new TextRun("Facility cost benchmarks and lease negotiation guidance for facility consolidation")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Organizational Scenarios: ", bold: true }), new TextRun("Impact modeling of headcount reductions and departmental restructuring")] }),
  new Paragraph({ children: [new TextRun({ text: "Supply Chain Optimization Tools: ", bold: true }), new TextRun("Procurement cost analysis and vendor consolidation opportunities")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What is our current annual OpEx by department and what is the bottom-up reduction target?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could we save 20-30% on COGS through manufacturing partner consolidation or CMO switching?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the optimal organizational structure post-failure given remaining portfolio programs?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Which functions could be partially or fully outsourced to reduce fixed costs?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could facility consolidation or geographic footprint reduction save $X M annually?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Cost reduction roadmap with specific initiatives, savings targets, and implementation timelines", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Organizational restructuring recommendations with FTE reductions and function realignment", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "COGS optimization analysis with preferred manufacturing partners and pricing models", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Outsourcing vs. insourcing decision matrix for key functions", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Facility consolidation and real estate optimization plan with lease renegotiation strategy", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Aggregate savings impact: monthly burn rate reduction and extended runway projection", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Cost reduction action plan with departmental breakdowns, cost driver analysis, and implementation Gantt charts.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 5: Financing & Capital Raising Strategy", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Develop comprehensive financing strategy to close capital gap created by top 2 program failures, balancing dilution, debt, partnerships, and asset sales.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "Current equity cap table, shareholder composition, and board preferences", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Existing debt obligations and covenant compliance status", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Current market valuation and comparable company valuations", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Investor appetite and available financing vehicles in current market environment", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Projected burn rate and capital requirements under cost reduction and acceleration scenarios", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Biotech Valuation Models: ", bold: true }), new TextRun("DCF, comparable company, and precedent transaction valuation analysis")] }),
  new Paragraph({ children: [new TextRun({ text: "Venture Capital Intelligence: ", bold: true }), new TextRun("Investor lists, deal types, and available financing rounds in current market")] }),
  new Paragraph({ children: [new TextRun({ text: "Debt Market Intelligence: ", bold: true }), new TextRun("Available loan and convertible debt options, interest rates, and covenant terms")] }),
  new Paragraph({ children: [new TextRun({ text: "IPO/Public Market Analysis: ", bold: true }), new TextRun("Feasibility assessment for potential secondary or IPO funding")] }),
  new Paragraph({ children: [new TextRun({ text: "Asset-Based Financing: ", bold: true }), new TextRun("Royalty monetization, asset securitization, and non-dilutive financing options")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Investor Network: ", bold: true }), new TextRun("Pre-qualified investor lists and relationships for crisis fundraising scenarios")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What is our current equity valuation and likely impact of dual program failure?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could we raise capital through equity financing without destroying shareholder value?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Are there non-dilutive financing options (debt, royalties, asset sales) we should prioritize?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What is the optimal capital structure: equity, debt, and partnership combinations?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Could we secure $X M in financing, and what dilution would result?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Scenario-based financial projections with and without capital raising", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Financing options analysis: equity raise, debt, partnerships, and asset sales with pros/cons", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Valuation analysis and dilution impact modeling for various equity raise scenarios", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Investor targeting strategy and pitch materials highlighting bridge programs and cost reductions", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Debt financing options with rate, covenant, and maturity term comparisons", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Recommended capital structure with timeline and key negotiation points", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Financial strategy document with valuation analysis, financing option matrices, and investor pitch summary.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stage 6: Backup Plan Integration & Crisis Management Implementation", style: "Heading2" }),
  new Paragraph({ children: [new TextRun({ text: "Purpose: ", bold: true }), new TextRun("Synthesize all contingency strategies into integrated backup plan with decision governance, stakeholder communication, implementation timeline, and trigger criteria.")] }),
  new Paragraph({ text: "Inputs:", bold: true }),
  new Paragraph({ text: "All Stage 1-5 outputs: financial impact, bridge programs, in-licensing opportunities, cost savings, and financing strategy", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Board and management decision criteria and risk tolerance", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stakeholder concerns: employees, investors, partners, and regulatory bodies", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Legal and contractual constraints on program termination and facility closure", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Market timing considerations and competitive landscape impacts", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Called:", bold: true }),
  new Paragraph({ children: [new TextRun({ text: "Crisis Management Framework: ", bold: true }), new TextRun("Decision trees and governance protocols for catastrophic failure scenarios")] }),
  new Paragraph({ children: [new TextRun({ text: "Stakeholder Communication Planning: ", bold: true }), new TextRun("Employee retention, investor relations, and partner notification strategies")] }),
  new Paragraph({ children: [new TextRun({ text: "Legal Contingency Analysis: ", bold: true }), new TextRun("Program termination, lease break, and employment law implications")] }),
  new Paragraph({ children: [new TextRun({ text: "Business Continuity Planning: ", bold: true }), new TextRun("Operational resilience and critical function backup procedures")] }),
  new Paragraph({ children: [new TextRun({ text: "Quiver Executive Dashboard: ", bold: true }), new TextRun("Real-time KPI monitoring and early warning signals for program failure risk")] }),
  new Paragraph({ children: [new TextRun({ text: "Integration Planning Tools: ", bold: true }), new TextRun("Merge of acquisition targets and in-licensed programs with existing organization")] }),
  new Paragraph({ text: "Exemplary Sub-Prompts:", bold: true }),
  new Paragraph({ text: "What is the comprehensive backup plan that would keep the company viable post-failure?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How should we communicate dual program failure to investors and employees?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What are the key decision gates and trigger criteria for activating backup plan elements?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "How should we sequence cost reductions, financing, and program acceleration decisions?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "What contingencies should we execute pre-emptively vs. only upon failure confirmation?", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Expected Outputs:", bold: true }),
  new Paragraph({ text: "Integrated backup plan document with recommended sequence of actions and decision criteria", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Crisis decision-making governance: authority levels, approval workflows, and escalation procedures", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Comprehensive implementation roadmap with phases, milestones, and responsibility assignments", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Stakeholder communication strategy: employee, investor, partner, and regulatory messages", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Financial projections under backup plan: runway, breakeven timeline, and path to sustainability", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Early warning indicator dashboard with monitoring metrics and escalation thresholds", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ children: [new TextRun({ text: "Format: ", bold: true }), new TextRun("Crisis management playbook with decision trees, communication templates, and implementation checklists.")] }),
  new Paragraph({ text: "", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Tools & Databases Summary", style: "Heading2" }),
  new Paragraph({ text: "Sapphire NPV Calculator: Risk-adjusted NPV computation integrating success probability, discount rates, commercial parameters, and market assumptions", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Financial Modeling System: Multi-scenario cash flow projections, balance sheet impact analysis, and P&L forecasting under various portfolio and market conditions", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Cortellis Market Intelligence: Peak sales estimates, market growth rates, pricing benchmarks, and competitive landscape data", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Historical Trial Outcomes Database: Phase-specific, indication-specific, and modality-specific failure rate data with root cause analysis", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quiver Financial Planning Tools: Cash flow stress-testing, runway extensions, and capital requirement modeling", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Industry Valuation Models: Comparable company analysis, precedent transaction data, and equity valuation impact modeling", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Sapphire Program Acceleration Engine: Timeline optimization algorithms and probability-of-success modeling by program and stage", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "BioPharma Intelligence Platform: Strategic partnership data, licensing deal terms, and M&A precedent valuations", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Drug Hunter & Excelra: Deal benchmarking and licensing valuation models across therapeutic areas", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Quiver Partner Network Database: Identified pharmaceutical and biotech partner profiles with development interests", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Regulatory Fast-Track Eligibility Assessment: Qualification criteria for breakthrough, orphan drug, and accelerated approval pathways", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Indication Mapping Tools: Off-label, adjacent indication, and repurposing opportunities for existing programs", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "BioPharma Licensing Intelligence: In-licensing opportunities, available programs, and licensing deal structure models", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "BioMedReports & Evaluate Pharma: Deal tracking, program availability, and transaction valuation benchmarks", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Biotech Cost Benchmarking Database: Departmental OpEx, FTE costs, overhead allocation, and industry cost drivers", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "Contract Manufacturing Analysis: COGS reduction, CMO alternatives, and supply chain optimization opportunities", numbering: { reference: "bullets", level: 0 } }),
  new Paragraph({ text: "CRO & Consulting Cost Models: Outsourcing options, service provider pricing, and insourcing vs. outsourcing decision matrices", numbering: { reference: "bullets", level: 0 } }),
];

const doc = new Document({
  numbering: { config: [{ reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "\u2022", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }, { level: 1, format: LevelFormat.BULLET, text: "\u2022", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1440, hanging: 360 } } } }] }] },
  styles: { default: { document: { run: { font: "Arial", size: 24 } } }, paragraphStyles: [{ id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial" }, paragraph: { spacing: { before: 240, after: 240 } } }, { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 28, bold: true, font: "Arial" }, paragraph: { spacing: { before: 200, after: 200 } } }] },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } }, children: paragraphs }]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync("/sessions/youthful-vigilant-planck/mnt/Desktop/Sapphire Prompt Work_Feb 2026/Sapphire Pipelines/Pipeline_154.docx", buffer);
  console.log("Pipeline_154.docx created with " + paragraphs.length + " paragraphs");
});
