# -*- coding: utf-8 -*-
"""
Bundle the orchestrator's end-to-end runs + Q-Models catalog into site/orchestrator_data.js.

Runs the ENGINE (sapphire-orchestrator/orchestrator.py) for each shipped scenario, so the site
Console renders EXACTLY what `python sapphire-orchestrator/run.py <id>` produces — one source of
truth for the front-facing and bucket-facing layers. Path-relative; runs anywhere.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ORCH = os.path.join(ROOT, "sapphire-orchestrator")
OUT = os.path.join(ROOT, "site", "orchestrator_data.js")

sys.path.insert(0, ORCH)
from orchestrator import ENGINE, SCENARIOS, _qmodels_catalog  # noqa: E402

scenarios = [ENGINE.run(sid) for sid in SCENARIOS]
catalog = _qmodels_catalog()

data = {"scenarios": scenarios, "catalog": catalog}
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by _build/build_orch_data.py — runs sapphire-orchestrator/orchestrator.py.\n")
    f.write("// Edit the engine or scenarios/*.json, not this file.\n")
    f.write("window.SAPPHIRE_ORCH = ")
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write(";\n")
print("wrote", OUT, "| scenarios:", len(scenarios), "| catalog:", len(catalog))
